### ISSUE TITLE
Batch generation of ULIDs not lexicographically sorted

### ISSUE THREAD

**Issue by AllioNicholas** [yaslab/ULID.swift#5]
It happened to generate multiple ULID close one another in time. The generated values are unique but not lexicographically sorted following the creation time.

A simple code snippet to reproduce it:
```
(0..<10).enumerated().forEach { idx, _ in
    print("\(ULID().ulidString) \(idx)")
}
```

Actual result | Index | Expected (sorted) result | Index
-- | :--: | -- | :--:
01EJV5K2N2CFMWZYK3Y5PJ0AP7 | **0** | 01EJV5K2N291CQVCD27RBEYHK1 | **5**
01EJV5K2N2WEGVVS98KQM319FJ | **1** | 01EJV5K2N2BJKRMEZ8FAQ4RT63 | **4**
01EJV5K2N2QT7P5QWA0SSHGB46 | **2** | 01EJV5K2N2CFMWZYK3Y5PJ0AP7 | **0**
01EJV5K2N2ENGKSZ5X1PXDYHWD | **3** | 01EJV5K2N2ENGKSZ5X1PXDYHWD | **3**
01EJV5K2N2BJKRMEZ8FAQ4RT63 | **4** | 01EJV5K2N2GBBVZR0B10MCGS71 | **7**
01EJV5K2N291CQVCD27RBEYHK1 | **5** | 01EJV5K2N2QT7P5QWA0SSHGB46 | **2**
01EJV5K2N2R0SQF0ZQQ3PXWFFJ | **6** | 01EJV5K2N2R0SQF0ZQQ3PXWFFJ | **6**
01EJV5K2N2GBBVZR0B10MCGS71 | **7** | 01EJV5K2N2WEGVVS98KQM319FJ | **1**
01EJV5K2N378YF8N4ATHJMKWMY | **8** | 01EJV5K2N36DPZHNZTKGMSJBV7 | **9**
01EJV5K2N36DPZHNZTKGMSJBV7 | **9** | 01EJV5K2N378YF8N4ATHJMKWMY | **8**

**Comment by AllioNicholas** [comment]
Any chance @yaslab or @adamrothman had a look at this..?

**Comment by yaslab** [comment]
The contents of the ULID are as follows. (The `Timestamp` is UNIX-time in milliseconds.)

```
 01EJV5K2N2      CFMWZYK3Y5PJ0AP7

|----------|    |----------------|
 Timestamp          Randomness
   48bits             80bits
```

So, ULIDs can be sorted in time order in milliseconds.  ULIDs generated within milliseconds can be lexicographically sorted as a string, but cannot be sorted by time.

**Comment by AllioNicholas** [comment]
Thanks for the explanation @yaslab
